/* Unit 1: The Language of Change (3 weeks, 12 sessions). Sessions 1-6 here; 7-12, Labor and Quest in unit1b.js */
window.OLY = window.OLY || {}; OLY.units = OLY.units || [];
OLY.units.push({
  id:'u1', num:1, title:'The Language of Change', subtitle:'Functions, graphs, slope, equations, and where two lines meet', weeks:3, badge:'cartographer',
  intro:`Three weeks. A function is a machine. A graph is a picture of a relationship. Slope is a rate. An equation is a question, and solving it is the answer. By the Labor you'll know whether Lamine Yamal can catch Cristiano Ronaldo with a head start, and you'll prove it three ways: algebra, a graph, and a spreadsheet.`,
  sessions:[
  // ---------------------------------------------------------------- S1
  {
    id:'u1s1', week:1, day:1, title:'The Machine', subtitle:'Functions: something goes in, a rule happens, something comes out', tags:['magic'],
    warmup:{ q:`A server earns a <b>$16.50/hour</b> base. Four hours of work: base pay?`, type:'num', ans:66, tol:0, reveal:`<b>$66.</b> 16.5 × 4. You just ran a function: hours in, dollars out.` },
    story:[
      {t:'h', html:'A function is a machine'},
      {t:'p', html:`<p>A vending machine: you press B4, you get the same chips every time. Press B4 and get a different snack each time and you'd call it broken. That reliability is the whole idea of a <b>function</b>: something goes in (the input), a rule happens, and exactly one thing comes out (the output). Same input, same output, every time.</p>`},
      {t:'decoder', term:'Function', def:`A rule that turns each input into exactly one output. Input → rule → output. If you know the rule and the input, you know the output.`, ex:`"Multiply by 3 and add 2" is a function. Put in 4, get 14. Put in 4 again tomorrow, still 14.`},
      {t:'decoder', term:'Expression', def:`A math phrase with no equals sign, like 3x + 2. It's a recipe, not a statement. You can evaluate it (plug in a number) but you can't "solve" it, because it isn't claiming anything.`, ex:`3x + 2 is an expression. 3x + 2 = 17 is an equation (it claims something, and it can be true or false).`},
      {t:'h', html:'Function notation: f(x)'},
      {t:'p', html:`<p>Mathematicians name their machines. <b>f(x) = 3x + 2</b> means: "the machine called f, when you feed it x, gives back 3x + 2." Then <b>f(4)</b> means "feed it 4," and f(4) = 3(4) + 2 = 14.</p><p>Read f(x) as "f of x." <b>It is not f times x.</b> This confuses everyone for about a week and then never again. The parentheses here mean "input goes here," like a slot.</p>`},
      {t:'formula', html:`f(x) = 3x + 2 &nbsp;&nbsp;&nbsp; f(4) = 3(4) + 2 = 14 &nbsp;&nbsp;&nbsp; f(10) = 32`},
      {t:'thread', kind:'example', title:'The server pay machine', html:`<p>A 5-hour shift at $16.50/hour is $82.50 base. Tips are about 18% of what the tables spend. So pay depends on sales, s:</p><div class="formula">P(s) = 82.5 + 0.18s</div><p>If the tables spend $600: P(600) = 82.5 + 0.18(600) = 82.5 + 108 = <b>$190.50</b>. If they spend $0 (dead night): P(0) = $82.50. The machine takes sales in and hands pay out. (Base rate is a stand-in; tipped wages vary by state. The 18% is real; that's what people tip.)</p>`},
      {t:'thread', kind:'example', title:'The storm machine', html:`<p>In Fortnite's first storm phase the storm does <b>1 HP per second</b>. Your health if you stand in it: H(t) = 100 − 1·t, where t is seconds. H(30) = 70. H(100) = 0, which is the game's polite way of saying you should have rotated.</p><p>By phase 4 it's 7 HP/s: H(t) = 100 − 7t. Same machine, meaner rule.</p>`},
      {t:'thread', kind:'story', title:'Who named it', html:`<p>Gottfried Leibniz used the word "function" in 1673 (he also invented calculus, which we'll get to, and had a legendary feud with Newton about it). Leonhard Euler gave us the f(x) notation in 1734. Euler wrote so much math that publishing his collected work took over a century. He also went blind and just kept going, dictating it.</p>`},
      {t:'thread', kind:'magic', title:'The trick is a chain of machines', html:`<p>"Double it, add 10, halve it, subtract the original" is four machines in a row: d(n) = 2n, then a(n) = n + 10, then h(n) = n ÷ 2, then s(n) = n − (original). Feeding the output of one machine into the next is called <b>composing</b> them. Every card trick you'll learn this year is a composition: shuffle, cut, deal, and somewhere in the chain the machines cancel out so the card ends up where you knew it would.</p>`},
      {t:'thread', kind:'paper', html:`Codex: <i>function</i>, <i>expression</i>, <i>f(x)</i>. Then draw three machines from your life as boxes with an arrow in and an arrow out: e.g. "jiujitsu classes per week → hours on the mat per month."`},
    ],
    practice:[
      { id:'u1s1p1', type:'num', xp:10, q:`f(x) = 3x + 2. Find <b>f(5)</b>.`, ans:17, tol:0, hints:[`Replace every x with 5.`,`3(5) + 2.`], sol:`3 × 5 + 2 = <b>17</b>.` },
      { id:'u1s1p2', type:'num', xp:10, q:`g(x) = x² − 1. Find <b>g(4)</b>.`, ans:15, tol:0, hints:[`Replace x with 4: 4² − 1.`,`4² = 16.`], sol:`16 − 1 = <b>15</b>.` },
      { id:'u1s1p3', type:'num', xp:10, q:`Server pay: P(s) = 82.5 + 0.18s. A slow night, $400 in sales. <b>P(400)</b> = ?`, ans:154.5, tol:0.01, unit:'dollars', hints:[`0.18 × 400 first.`,`72. Then add the base.`], sol:`82.5 + 72 = <b>$154.50</b>.` },
      { id:'u1s1p4', type:'num', xp:10, q:`Fortnite phase 3 storm: 5 HP/s. H(t) = 100 − 5t. Your health after 12 seconds in the storm: <b>H(12)</b> = ?`, ans:40, tol:0, unit:'HP', hints:[`5 × 12 = 60.`], sol:`100 − 60 = <b>40 HP</b>. Rotate.` },
      { id:'u1s1p5', type:'mc', xp:10, q:`Spider-Man's web cartridge holds <b>200 shots</b>. Each swing uses <b>3</b>. Which rule gives shots left after n swings?`, choices:[`S(n) = 200 + 3n`,`S(n) = 200 − 3n`,`S(n) = 3n − 200`,`S(n) = 200 ÷ 3n`], ans:1, hints:[`Shots go <i>down</i> as swings go up.`,`Start at 200, lose 3 per swing.`], sol:`Start with 200, subtract 3 for each swing: <b>S(n) = 200 − 3n</b>.` },
      { id:'u1s1p6', type:'num', xp:10, q:`Using S(n) = 200 − 3n, how many shots are left after <b>50 swings</b>?`, ans:50, tol:0, hints:[`3 × 50.`], sol:`200 − 150 = <b>50 shots</b>. Time to reload. (Tom Holland's Peter would have run out sooner; he wastes a lot on quips.)` },
      { id:'u1s1p7', type:'num', xp:10, q:`In Minecraft, walking speed is <b>4.317 blocks per second</b> (a block is one meter). Distance walked: D(t) = 4.317t. <b>D(60)</b> = ? (Nearest whole block.)`, ans:259, tol:1, unit:'blocks', hints:[`4.317 × 60.`,`Estimate first: 4 × 60 = 240, and a bit more.`], sol:`4.317 × 60 = <b>259 blocks</b> in a minute of walking.` },
      { id:'u1s1p8', type:'num', xp:10, q:`In Harry Potter's world, 29 Knuts make a Sickle and 17 Sickles make a Galleon, so a Galleon is 17 × 29 = 493 Knuts. Knuts in g Galleons: K(g) = 493g. <b>K(3)</b> = ?`, ans:1479, tol:0, unit:'Knuts', hints:[`493 × 3.`,`Estimate: 500 × 3 = 1,500, minus a bit.`], sol:`493 × 3 = <b>1,479 Knuts</b>. Goblin accountants have a hard job.` },
    ],
    apply:{ title:'Machines in a Sheet', intro:`<p>Sheets is a function machine with a memory. Build one.</p>`,
      steps:[`New tab in your Olympus sheet. A1: "x". B1: "f(x) = 3x + 2".`,`A2 through A11: the numbers 1 to 10. (Type 1 and 2, select both, drag the corner down.)`,`B2: <code>=3*A2+2</code>. Press Enter. Drag B2's corner down to B11. You just evaluated f(1) through f(10) in two seconds.`,`Column C: the server pay machine. C1: "P(s)". Put sales 0, 100, 200 ... 1000 in column D, and in C: <code>=82.5+0.18*D2</code>, filled down.`,`Column E: the storm. E2: <code>=100-5*A2</code>. Where does it hit zero? (It doesn't in 10 seconds. Extend A to 20.)`],
      checklist:[`f(x) column built with a formula and filled down`,`Server pay table for sales 0 to 1000`,`Storm health column, extended until it reaches 0`],
      dad:`Make sure the formulas reference cells (A2), not typed numbers. Ask him: "If I change the 3 to a 5, what happens to the whole column?" and have him do it.`
    },
  },
  // ---------------------------------------------------------------- S2
  {
    id:'u1s2', week:1, day:2, title:'Pictures of Relationships', subtitle:'Descartes, the fly on the ceiling, and why a graph is worth a thousand numbers', tags:['greek'],
    warmup:{ q:`In your head: the point <b>(3, −2)</b> is where, relative to the axes?`, type:'mc', choices:[`Right of the y-axis, above the x-axis`,`Right of the y-axis, below the x-axis`,`Left of the y-axis, below the x-axis`,`Left of the y-axis, above the x-axis`], ans:1, reveal:`<b>Right and below.</b> x = 3 means 3 steps right; y = −2 means 2 steps down.` },
    story:[
      {t:'thread', kind:'story', title:'The fly on the ceiling', html:`<p>René Descartes liked to sleep late. The story (possibly true, definitely told a lot) is that he was lying in bed one morning in 1637 watching a fly wander around the ceiling, and it hit him: he could describe exactly where the fly was with just two numbers, its distance from one wall and its distance from another. Two numbers, one point. And if the fly moved in a pattern, the pattern could be written as an equation.</p><p>That's the <b>Cartesian plane</b> (named after him). It's the bridge between algebra (equations) and geometry (pictures). Before Descartes they were separate subjects. After him, every equation had a shape and every shape had an equation.</p>`},
      {t:'decoder', term:'Coordinate plane', def:`Two number lines crossing at right angles. The horizontal one is the x-axis, the vertical one is the y-axis, and the crossing point is the origin (0, 0). Every point gets an address: (x, y), always x first.`, ex:`(3, 25.5) means "3 across, 25.5 up." On a distance-time graph that could be "at 3 seconds, 25.5 meters."`},
      {t:'h', html:'A graph is a picture of a function'},
      {t:'p', html:`<p>Take a machine, feed it lots of inputs, and plot every (input, output) pair as a point. Connect them. That picture <i>is</i> the function. You can read outputs off it without calculating, see where it's rising or falling, and compare two machines at a glance.</p>`},
      {t:'thread', kind:'example', title:"Messi's sprint", html:`<p>Messi's top recorded speed at the 2026 World Cup was 30.9 km/h, about 8.5 m/s. Suppose he's already at top speed and sprinting for the ball. Every second, 8.5 more meters.</p>
        <table><tr><th>t (seconds)</th><td>0</td><td>1</td><td>2</td><td>3</td><td>4</td></tr><tr><th>d (meters)</th><td>0</td><td>8.5</td><td>17</td><td>25.5</td><td>34</td></tr></table>
        <p>The machine is d(t) = 8.5t. Plot it:</p>`},
      {t:'plot', spec:{ x:[0,5], y:[0,50], xl:'t (seconds)', yl:'d (meters)', lines:[{f:t=>8.5*t, label:'Messi: d = 8.5t', lx:4.2}], points:[[1,8.5],[2,17],[3,25.5,'(3, 25.5)'],[4,34]] }},
      {t:'p', html:`<p>Straight line. That's what constant speed looks like. Read it: at t = 2, d = 17. Where is he at t = 3.5? Halfway between 25.5 and 34: about 30. You didn't calculate, you <i>looked</i>.</p>`},
      {t:'decoder', term:'Linear', def:`A function whose graph is a straight line. It changes by the same amount every step. Constant speed is linear. A fixed hourly wage is linear. Storm damage in one phase is linear.`, ex:`d = 8.5t adds 8.5 every second. Linear. d = 4.9t² adds more each second (a falling ball). Not linear.`},
      {t:'thread', kind:'example', title:'Not everything is a line', html:`<p>Drop a ball off a Fortnite cliff (or jump from the Battle Bus with your glider closed). Distance fallen is d = 4.9t². Compare it to Messi:</p>`},
      {t:'plot', spec:{ x:[0,5], y:[0,50], xl:'t (seconds)', yl:'d (meters)', lines:[{f:t=>8.5*t, label:'Messi', lx:4.4},{f:t=>4.9*t*t, label:'falling ball', lx:2.6}] }},
      {t:'p', html:`<p>The ball starts slow and gets faster; the line bends. That bend is <b>acceleration</b>, and it's Unit 4. For now: straight line means steady rate. Curve means the rate is changing.</p>`},
      {t:'thread', kind:'greek', title:'Why is it called geometry?', html:`<p><i>Geo</i> = earth, <i>metron</i> = measure. The Greeks (and the Egyptians before them) invented it to re-survey farmland after the Nile flooded every year and washed away the boundary markers. Descartes' trick was realizing that measuring the earth and doing algebra were the same activity. Thales, Euclid, and Archimedes had the shapes; Descartes gave them coordinates.</p>`},
      {t:'thread', kind:'paper', html:`Graph paper. Plot Messi's table by hand: axes labeled with units, points marked, line drawn with a ruler. Then plot Lamine Yamal (35.5 km/h ≈ 9.9 m/s) on the same axes: at t = 1, 2, 3, 4 he's at 9.9, 19.8, 29.7, 39.6. Which line is steeper?`},
    ],
    practice:[
      { id:'u1s2p1', type:'num', xp:10, q:`In the point <b>(4, 9)</b>, what is the x-coordinate?`, ans:4, tol:0, hints:[`x always comes first.`], sol:`<b>4</b>. (Alphabetical: x before y.)` },
      { id:'u1s2p2', type:'mc', xp:10, q:`f(x) = 2x + 1. Which point is on its graph?`, choices:[`(3, 7)`,`(3, 6)`,`(7, 3)`,`(2, 4)`], ans:0, hints:[`Plug the x-value in and see if you get the y-value.`,`f(3) = 2(3) + 1 = ?`], sol:`f(3) = 7, so <b>(3, 7)</b> is on the graph. (7, 3) is not: f(7) = 15.` },
      { id:'u1s2p3', type:'num', xp:10, q:`Messi at 8.5 m/s: how far at <b>t = 4</b>?`, ans:34, tol:0, unit:'m', hints:[`d = 8.5t.`], sol:`8.5 × 4 = <b>34 m</b>. Also readable straight off the table.` },
      { id:'u1s2p4', type:'num', xp:10, q:`From the graph of d = 8.5t: at what time is Messi at <b>25.5 m</b>?`, ans:3, tol:0, unit:'s', hints:[`Find 25.5 on the vertical axis, go across to the line, drop down.`,`Or: 25.5 ÷ 8.5.`], sol:`<b>3 seconds</b>. Reading a graph backwards (output → input) is something you'll do constantly.` },
      { id:'u1s2p5', type:'num', xp:10, q:`Yamal at <b>9.86 m/s</b> (35.5 km/h, fastest of the Spain squad at the 2026 World Cup): how far after 3 seconds? One decimal.`, ans:29.6, tol:0.1, unit:'m', hints:[`9.86 × 3.`], sol:`<b>29.6 m</b>. About 4 meters ahead of Messi at the same moment. Messi would say he doesn't need to sprint; the ball comes to him.` },
      { id:'u1s2p6', type:'mc', xp:10, q:`Two distance-time lines on the same axes: Yamal's and Messi's. Which is steeper, and why?`, choices:[`Yamal's, because he covers more meters per second`,`Messi's, because he has more goals`,`They're the same; both are straight`,`Neither; steepness depends on the units`], ans:0, hints:[`Steeper = more rise per step across.`], sol:`<b>Yamal's.</b> More meters per second means the line climbs faster. Steepness is speed. Tomorrow has a name for that.` },
      { id:'u1s2p7', type:'num', xp:10, q:`Every point that sits <i>on the y-axis</i> has what x-coordinate?`, ans:0, tol:0, hints:[`The y-axis is the vertical line through the origin. How far left or right is it?`], sol:`<b>0</b>. Points on the y-axis look like (0, something). The place a line crosses the y-axis will matter a lot in Session 5.` },
    ],
    apply:{ title:'Desmos: your first graph', intro:`<p>Open <b>desmos.com/calculator</b> (free, no account needed). It's a graphing calculator that lives in a browser.</p>`,
      steps:[`Type <code>y = 8.5x</code>. There's Messi.`,`Below it type <code>y = 9.86x</code>. There's Yamal.`,`Type <code>(3, 25.5)</code>. A point appears. Is it on Messi's line?`,`Click the wrench (top right) to set the axes: x from 0 to 5, y from 0 to 50.`,`Now type <code>y = 4.9x^2</code>. Watch the ball fall. Where does it cross Messi's line? (Hover the intersection; Desmos will show you.)`,`Screenshot, print or sketch it into the notebook next to your hand-drawn version.`],
      checklist:[`Both sprint lines graphed in Desmos`,`Point (3, 25.5) checked against Messi's line`,`Hand-drawn graph on paper with labeled axes`],
      dad:`The hand-drawn one matters more than the Desmos one. Check that the axes have units and the scale is even (each grid square worth the same amount). Uneven scales are the number one way kids lie to themselves with graphs.`
    },
  },
  // ---------------------------------------------------------------- S3
  {
    id:'u1s3', week:1, day:3, title:'Slope Is a Rate', subtitle:'Rise over run, and why it is secretly velocity', tags:['matmath'],
    warmup:{ q:`Convert <b>36 km/h</b> to meters per second.`, type:'num', ans:10, tol:0, reveal:`<b>10 m/s.</b> 36 km = 36,000 m; an hour = 3,600 s; 36,000 ÷ 3,600 = 10. Shortcut you'll use forever: <b>km/h ÷ 3.6 = m/s</b>.` },
    story:[
      {t:'h', html:'Slope: how steep, and in which direction'},
      {t:'p', html:`<p>Yesterday you saw that Yamal's line is steeper than Messi's because he covers more meters per second. Today we measure steepness.</p>`},
      {t:'decoder', term:'Slope', def:`How much a line rises for each step it runs. Slope = rise ÷ run = (change in y) ÷ (change in x). Pick any two points on the line and compute it; you'll get the same number.`, ex:`From (1, 8.5) to (3, 25.5): rise = 25.5 − 8.5 = 17, run = 3 − 1 = 2, slope = 17 ÷ 2 = 8.5.`},
      {t:'formula', html:`m = <span class="frac"><span>y<sub>2</sub> − y<sub>1</sub></span><span>x<sub>2</sub> − x<sub>1</sub></span></span> = <span class="frac"><span>Δy</span><span>Δx</span></span> = <span class="frac"><span>rise</span><span>run</span></span>`},
      {t:'decoder', term:'Δ (delta)', def:`The Greek letter D, used to mean "change in." Δy is "the change in y." It's not a variable; it's a label that says "subtract the before from the after."`, ex:`If your health goes from 100 to 40, ΔH = 40 − 100 = −60. Negative, because it went down.`},
      {t:'decoder', term:'Rate', def:`A change in one thing per unit of another. Meters per second. Dollars per hour. HP per second. Every rate is a slope, and every slope is a rate.`, ex:`8.5 m/s is a rate. On a distance-time graph it's the slope. Same thing, two names.`},
      {t:'h', html:'Slope is velocity'},
      {t:'p', html:`<p>Here's the payoff. On a distance-vs-time graph, rise is meters and run is seconds, so slope is meters per second. <b>The slope of a position graph is the velocity.</b> Not "related to." Is. This is the first sentence of physics and the first sentence of calculus, and you just learned it from Messi.</p><p>In <i>Project Hail Mary</i>, Ryland Grace spends half the book staring at graphs and reading slopes off them to figure out how fast Astrophage is growing or how fast the Hail Mary is going. The whole plot runs on this.</p>`},
      {t:'thread', kind:'example', title:'The 2026 World Cup speed board (real data, FIFA/Sofascore)', html:`<table><tr><th>Player</th><th>km/h</th><th>÷ 3.6 → m/s</th></tr><tr><td>Kylian Mbappé</td><td>37.6</td><td>10.44</td></tr><tr><td>Achraf Hakimi</td><td>35.6</td><td>9.89</td></tr><tr><td>Erling Haaland</td><td>35.6</td><td>9.89</td></tr><tr><td>Lamine Yamal</td><td>35.5</td><td>9.86</td></tr><tr><td>Harry Kane</td><td>31.4</td><td>8.72</td></tr><tr><td>Lionel Messi</td><td>30.9</td><td>8.58</td></tr></table><p>Cristiano Ronaldo's famous number is 33.95 km/h, clocked at the 2018 World Cup when he was 33 years old. He wasn't on the 2026 board. He is 41.</p>`},
      {t:'thread', kind:'example', title:'Negative slope: the storm', html:`<p>Fortnite's first storm circle takes 90 seconds to shrink (that's the real Chapter 7 timing). Say the safe zone's radius goes from 1,500 m down to 900 m in those 90 seconds. Slope = (900 − 1,500) ÷ 90 = −600 ÷ 90 = <b>−6.67 m/s</b>. Negative, because the radius is falling. The storm edge moves inward at about 6.7 meters per second. You sprint at maybe 6 m/s. Do the math on whether to loot that chest.</p>`},
      {t:'plot', spec:{ x:[0,90], y:[0,1600], xl:'t (seconds)', yl:'safe zone radius (m)', lines:[{f:t=>1500-6.667*t, label:'radius = 1500 − 6.67t', lx:20}], points:[[0,1500],[90,900]] }},
      {t:'thread', kind:'matmath', title:'The shot', html:`<p>A double-leg takedown: you drop your level and drive about 1.5 meters into your partner in about half a second. Average speed = 1.5 ÷ 0.5 = <b>3 m/s</b>. Slow compared to Messi, but Messi isn't trying to move a person. Thursday's Lab Day: time five of your own shots (phone stopwatch, or better, slow-mo video) and get your real number. That's the Mat Scientist badge.</p>`},
      {t:'thread', kind:'paper', html:`Codex: <i>slope</i>, <i>Δ</i>, <i>rate</i>. Draw a rise-over-run triangle on yesterday's Messi graph, between t = 1 and t = 3. Label rise and run with units.`},
    ],
    practice:[
      { id:'u1s3p1', type:'num', xp:10, q:`Slope of the line through <b>(1, 8.5)</b> and <b>(3, 25.5)</b>.`, ans:8.5, tol:0.01, hints:[`Rise: 25.5 − 8.5. Run: 3 − 1.`,`17 ÷ 2.`], sol:`17 ÷ 2 = <b>8.5</b>. Messi's speed, read off two points.` },
      { id:'u1s3p2', type:'num', xp:10, q:`Storm phase 3: health goes from <b>(0 s, 100 HP)</b> to <b>(20 s, 0 HP)</b>. Slope?`, ans:-5, tol:0.01, unit:'HP/s', hints:[`Rise = 0 − 100 (it's negative).`,`Run = 20.`], sol:`−100 ÷ 20 = <b>−5 HP/s</b>. Matches the phase 3 damage rate. Slope of health vs. time is damage rate.` },
      { id:'u1s3p3', type:'num', xp:10, q:`Convert Ronaldo's <b>33.95 km/h</b> to m/s. Two decimals.`, ans:9.43, tol:0.02, unit:'m/s', hints:[`Divide by 3.6.`], sol:`33.95 ÷ 3.6 = <b>9.43 m/s</b>. Hold onto this; he's in the Labor.` },
      { id:'u1s3p4', type:'num', xp:10, q:`Storm phase 2 shrinks for 75 seconds. Say the radius goes from <b>1,200 m to 600 m</b>. Slope, in m/s?`, ans:-8, tol:0.01, unit:'m/s', hints:[`(600 − 1200) ÷ 75.`], sol:`−600 ÷ 75 = <b>−8 m/s</b>. Faster than you can run. Leave early.` },
      { id:'u1s3p5', type:'num', xp:10, tags:['matmath'], q:`A double-leg shot: <b>1.5 m in 0.5 s</b>. Average speed?`, ans:3, tol:0.01, unit:'m/s', hints:[`Distance ÷ time.`], sol:`<b>3 m/s</b>. (Slope of your position graph during the shot.)` },
      { id:'u1s3p6', type:'num', xp:10, q:`Minecraft sprint-jumping averages <b>7.127 m/s</b>. The line through (0, 0) and (10, ?): what's the missing y? Two decimals.`, ans:71.27, tol:0.05, unit:'blocks', hints:[`Slope × run = rise.`,`7.127 × 10.`], sol:`<b>71.27 blocks</b> in 10 seconds. Sprint-jumping is also the most efficient way to travel per hunger point, which is a slope of a different graph.` },
      { id:'u1s3p7', type:'mc', xp:10, q:`Line A has slope 4. Line B has slope 9. Both are distance vs. time. Which is faster?`, choices:[`A`,`B`,`Same speed`,`Can't tell without the intercept`], ans:1, hints:[`Slope is speed.`], sol:`<b>B.</b> 9 meters per second beats 4. The intercept (where it starts) doesn't change the speed.` },
      { id:'u1s3p8', type:'mc', xp:10, q:`A distance-time line with <b>zero slope</b> (flat) means:`, choices:[`Standing still`,`Moving backward`,`Infinite speed`,`Moving at 1 m/s`], ans:0, hints:[`No rise means no change in distance.`], sol:`<b>Standing still.</b> Distance isn't changing as time passes. A vertical line would be "infinite speed," which is why you'll never see one on a real position graph.` },
    ],
    apply:{ title:'The speed board in Sheets', intro:`<p>Turn the World Cup table into a working model.</p>`,
      steps:[`New tab: "Speed board." Column A: the six players plus Ronaldo. Column B: km/h (real numbers from the story).`,`C2: <code>=B2/3.6</code>. Fill down. That's m/s.`,`D2: <code>=30/C2</code>. Fill down. That's seconds to sprint 30 meters at top speed. Format to 2 decimals.`,`Select A1:D8, Data → Sort range by column D. Who's first? Who's last?`,`Insert → Chart. Make a bar chart of column C. Title it. Screenshot it into the notebook.`,`Desmos: type <code>y = mx</code>, click "add slider" for m. Drag m from 0 to 12. Watch the line tilt. That slider is speed.`],
      checklist:[`Speed board with formulas for m/s and 30 m time`,`Sorted fastest to slowest`,`Chart made`,`Desmos slope slider tried`],
      dad:`Ask: "If I add a player at 40 km/h, what happens?" (He should just add a row. If he wants to retype formulas, the lesson hasn't landed.) Also: Bolt's 100 m record averaged about 37.6 km/h over the whole race, with a peak near 44. Mbappé's 37.6 is a peak, not an average. Good dinner-table fact.`
    },
  },
  // ---------------------------------------------------------------- S4
  {
    id:'u1s4', week:1, day:4, lab:true, title:"Lab Day: Galileo's Ramp", subtitle:'Measure motion with your own hands, plot it, and find the slope', tags:['sheets','matmath'],
    warmup:{ q:`A ball rolls <b>2 meters in 4 seconds</b>. Average speed?`, type:'num', ans:0.5, tol:0.001, reveal:`<b>0.5 m/s.</b> Distance ÷ time. "Average" because it may have been speeding up the whole way, which is exactly what you're about to see.` },
    story:[
      {t:'thread', kind:'story', title:'Galileo slows down gravity', html:`<p>Around 1600, Galileo wanted to know how falling things move. Problem: they fall too fast to time, and there were no stopwatches. So he tilted the problem: roll a ball down a gentle ramp, which is falling in slow motion. For a clock, he let water flow from a jug into a cup while the ball rolled, then <i>weighed the water</i>. More water, more time. Crude, brilliant, and it worked.</p><p>He found something strange: the ball didn't cover equal distances in equal times. In the second second it went three times as far as in the first; in the third second, five times. Distance grew with the <b>square</b> of time. Nobody had ever measured that. It's the first equation of physics, and it's Unit 4's whole plot. Today you just need to see the curve with your own eyes.</p>`},
      {t:'h', html:'The experiment'},
      {t:'p', html:`<p><b>Materials:</b> a board, shelf, or long Lego baseplate as a ramp (1 to 2 meters), propped a few centimeters high at one end (gentle!); a marble, golf ball, or Rubik's-cube-sized ball; masking tape; a tape measure; a phone with a stopwatch, or better, slow-motion video.</p>
        <ol class="steps"><li>Tape marks every 20 cm along the ramp from the top: 0, 20, 40, ... up to 160 cm or whatever fits.</li><li>Release the ball from the top (don't push it). Start the timer at release.</li><li>Record the time when it passes each mark. Easiest with slow-mo video: film once, then scrub through and read the phone's timestamps. Stopwatch works too; just repeat each run 3 times and average.</li><li>Table in your notebook: t (s) and d (m). Convert cm to m.</li><li>Plot d vs. t on graph paper. Points, then connect them. Does it curve?</li><li>Compute the slope between the <i>last two</i> points and between the <i>first two</i>. Different? That difference is Galileo's discovery.</li></ol>`},
      {t:'thread', kind:'example', title:'What you should see (sample data)', html:`<table><tr><th>t (s)</th><td>0</td><td>0.5</td><td>1.0</td><td>1.5</td><td>2.0</td></tr><tr><th>d (m)</th><td>0</td><td>0.1</td><td>0.4</td><td>0.9</td><td>1.6</td></tr></table><p>Your numbers will differ (steeper ramp, faster), but the <i>shape</i> should match: bending upward. Use this sample data for the Practice problems if your run isn't finished yet.</p>`},
      {t:'plot', spec:{ x:[0,2.2], y:[0,2], xl:'t (seconds)', yl:'d (meters)', lines:[{f:t=>0.4*t*t, label:'sample: d = 0.4t²', lx:1.3}], points:[[0.5,0.1],[1,0.4],[1.5,0.9],[2,1.6]] }},
      {t:'h', html:'Sheets: let the computer find the slope'},
      {t:'p', html:`<p>Type your t values in column A and d values in column B. Then in any cell: <code>=SLOPE(B2:B6, A2:A6)</code>. Sheets fits the best straight line through your points and gives its slope: your <i>average</i> speed over the run. (Note the order: y-range first, then x-range. Everyone gets this backwards once.) Then insert a scatter chart and look at the curve.</p>`},
      {t:'thread', kind:'matmath', title:'Mat Math data night', html:`<p>At jiujitsu this week: film five of your shots or a sprint across the mat in slow-mo. Mark the start and end points; measure the distance with a tape (or count mat squares; a standard mat tile is 1 m). Read the time off the video. Compute your speed for each. Enter them in the sheet; <code>=AVERAGE()</code> them. That's real data, and it's the Mat Scientist badge.</p>`},
    ],
    practice:[
      { id:'u1s4p1', type:'num', xp:10, q:`Using the sample data: average speed over the whole run (1.6 m in 2.0 s)?`, ans:0.8, tol:0.01, unit:'m/s', hints:[`Distance ÷ time.`], sol:`1.6 ÷ 2 = <b>0.8 m/s</b>.` },
      { id:'u1s4p2', type:'num', xp:10, q:`Slope between the <b>last two</b> sample points, (1.5, 0.9) and (2.0, 1.6)?`, ans:1.4, tol:0.01, unit:'m/s', hints:[`Rise: 1.6 − 0.9. Run: 0.5.`], sol:`0.7 ÷ 0.5 = <b>1.4 m/s</b>.` },
      { id:'u1s4p3', type:'num', xp:10, q:`Slope between the <b>first two</b> sample points, (0, 0) and (0.5, 0.1)?`, ans:0.2, tol:0.01, unit:'m/s', hints:[`0.1 ÷ 0.5.`], sol:`<b>0.2 m/s</b>. Seven times slower than at the end. Same ball, same ramp.` },
      { id:'u1s4p4', type:'mc', xp:10, q:`The slope keeps increasing along the run. The ball is:`, choices:[`Speeding up`,`Slowing down`,`Moving at constant speed`,`Stopped`], ans:0, hints:[`Slope is speed. Increasing slope means...`], sol:`<b>Speeding up.</b> That's acceleration, and it's why the graph curves instead of drawing a line. Galileo saw exactly this.` },
      { id:'u1s4p5', type:'mc', xp:10, tags:['sheets'], q:`Times are in A2:A6 and distances in B2:B6. Which formula gives the slope?`, choices:[`=SLOPE(A2:A6, B2:B6)`,`=SLOPE(B2:B6, A2:A6)`,`=SLOPE(A2:B6)`,`=RISE(B2:B6)/RUN(A2:A6)`], ans:1, hints:[`Sheets wants the y-values first.`], sol:`<b>=SLOPE(B2:B6, A2:A6)</b>: y-range, then x-range. Distance is y (it depends on time), time is x.` },
    ],
    apply:{ title:'Run it, plot it, sheet it', intro:`<p>The Practice above used sample data. Now do it for real.</p>`,
      steps:[`Run the ramp experiment. At least 5 marks, at least 2 runs each.`,`Hand-plot in the notebook. Ruler for axes. No ruler for the curve.`,`Enter the data in a new "Ramp" tab. <code>=SLOPE()</code> for the average speed. Insert a scatter chart.`,`Write two sentences in the log: what the curve means, and one thing that went wrong in the measurement.`,`<b>Beat Dad Friday</b>: go to the Beat Dad page. Week 1's problem is live. Dad logs in as himself for his turn.`,`Check the cloud chip at the top says <b>saved</b>. (No cloud? Save a progress file to the Math Program folder.)`],
      checklist:[`Ramp data collected (5+ points)`,`Hand plot with labeled axes`,`Sheet with SLOPE and a chart`,`Beat Dad Week 1 done`,`Progress saved (cloud chip says saved, or progress file saved)`],
      dad:`Keep the ramp gentle (5 to 10 cm rise over a meter) or the times are too short to measure. Slow-mo video on the iPhone is 240 fps, which is plenty. If the curve isn't obvious, the ramp is too steep or the marks are too close together. Mat Scientist badge: award it once he brings real timing data from class into the sheet.`
    },
  },
  // ---------------------------------------------------------------- S5
  {
    id:'u1s5', week:2, day:1, title:'y = mx + b', subtitle:'Every straight line has a starting point and a rate. Learn to read both.', tags:['greek'],
    warmup:{ q:`P = 82.5 + 0.18s. If sales are <b>zero</b>, what's the pay?`, type:'num', ans:82.5, tol:0.01, reveal:`<b>$82.50.</b> The base. That number has a name today: the intercept.` },
    story:[
      {t:'h', html:'The anatomy of a line'},
      {t:'formula', html:`y = mx + b &nbsp;&nbsp;&nbsp;&nbsp; m = slope (the rate) &nbsp;&nbsp;&nbsp;&nbsp; b = y-intercept (where it starts)`},
      {t:'decoder', term:'y-intercept', def:`Where the line crosses the y-axis: the value of y when x = 0. In a real situation it's the starting amount, the flat fee, the head start, the base pay.`, ex:`In P = 0.18s + 82.5, the intercept is 82.5: what you're paid before a single table tips. In r = 1500 − 6.67t, it's 1500: the radius when the shrink starts.`},
      {t:'p', html:`<p>Every linear situation in the world has these two parts. <b>b</b> answers "where does it start?" and <b>m</b> answers "how fast does it change?" Once you can spot them in a sentence, you can write the equation in ten seconds.</p>
      <table><tr><th>Situation</th><th>b (start)</th><th>m (rate)</th><th>Equation</th></tr>
      <tr><td>Server: $82.50 base + 18% of sales</td><td>82.5</td><td>0.18 per dollar</td><td>P = 0.18s + 82.5</td></tr>
      <tr><td>Storm: 1,500 m radius, shrinking 6.67 m/s</td><td>1500</td><td>−6.67 per second</td><td>r = −6.67t + 1500</td></tr>
      <tr><td>Filament: $20 per kg plus $5 shipping</td><td>5</td><td>20 per kg</td><td>C = 20k + 5</td></tr>
      <tr><td>Rubik's: 60 s average, improving 2 s per week</td><td>60</td><td>−2 per week</td><td>T = −2w + 60</td></tr></table>`},
      {t:'thread', kind:'example', title:'Reading it off a graph', html:`<p>Given a line, find b by looking where it hits the y-axis. Find m with a rise-over-run triangle anywhere on it. Below: the line crosses at 40 and climbs 20 for every 10 across, so m = 2 and the equation is y = 2x + 40.</p>`},
      {t:'plot', spec:{ x:[0,30], y:[0,120], xl:'x', yl:'y', lines:[{f:x=>2*x+40, label:'y = 2x + 40', lx:18}], points:[[0,40,'b = 40'],[10,60],[20,80]] }},
      {t:'thread', kind:'greek', title:'Zeus refinances Olympus', html:`<p>Zeus takes out a loan to renovate the throne room (gold leaf, a bigger lightning-bolt rack). He owes 12,000 drachmas and pays 400 a month. What he still owes after n months: <b>D = −400n + 12,000</b>. Intercept: the original debt. Slope: negative, because it's shrinking. He'll be debt-free at n = 30. Hera thinks the rack was unnecessary.</p><p class="joke">Real loans have interest, which makes this not a line. That's Unit 2, and it's why the bank always wins.</p>`},
      {t:'thread', kind:'paper', html:`Codex: <i>y-intercept</i>, <i>slope-intercept form</i>. Then write three y = mx + b situations from your own life (phone plan? allowance plus chores? belt promotions?) with b and m labeled.`},
    ],
    practice:[
      { id:'u1s5p1', type:'num', xp:10, q:`y = 4x + 7. The slope is:`, ans:4, tol:0, hints:[`The number multiplying x.`], sol:`<b>4</b>.` },
      { id:'u1s5p2', type:'num', xp:10, q:`y = 4x + 7. The y-intercept is:`, ans:7, tol:0, hints:[`The number by itself: y when x = 0.`], sol:`<b>7</b>.` },
      { id:'u1s5p3', type:'mc', xp:10, q:`A line passes through <b>(0, 12)</b> with slope <b>3</b>. Its equation?`, choices:[`y = 12x + 3`,`y = 3x + 12`,`y = 3x − 12`,`y = x + 15`], ans:1, hints:[`(0, 12) is on the y-axis, so 12 is the intercept.`], sol:`<b>y = 3x + 12.</b>` },
      { id:'u1s5p4', type:'mc', xp:10, q:`A 6-hour shift at $16.50/hour gives $99 base, plus 18% of sales. Pay as a function of sales s:`, choices:[`P = 99s + 0.18`,`P = 0.18s + 99`,`P = 18s + 99`,`P = 0.18(s + 99)`], ans:1, hints:[`Start (b) is the base. Rate (m) is the tip fraction.`,`18% = 0.18.`], sol:`<b>P = 0.18s + 99.</b> Watch out for 18 vs 0.18: an 18 would mean tips of $18 per dollar spent, which is a restaurant you should open.` },
      { id:'u1s5p5', type:'num', xp:10, q:`Filament: C = 20k + 5 (dollars, k in kg). Cost of <b>3.5 kg</b>?`, ans:75, tol:0.01, unit:'dollars', hints:[`20 × 3.5, then add 5.`], sol:`70 + 5 = <b>$75</b>. About enough filament for 35 Cartographer badge tokens, or one very large Lego brick.` },
      { id:'u1s5p6', type:'num', xp:10, q:`Rubik's average: T = 60 − 2w. After <b>10 weeks</b>?`, ans:40, tol:0, unit:'seconds', hints:[`2 × 10 = 20.`], sol:`60 − 20 = <b>40 s</b>. (The world record is around 3 seconds. The line can't go on forever; at some point it has to bend. Everything linear is linear only for a while.)` },
      { id:'u1s5p7', type:'num', xp:10, q:`Storm: r = 1500 − 6.67t. Radius after <b>60 seconds</b>? Nearest meter.`, ans:1100, tol:1, unit:'m', hints:[`6.67 × 60.`,`About 400.`], sol:`1500 − 400 = <b>1,100 m</b> (1,099.8 to be fussy).` },
      { id:'u1s5p8', type:'mc', xp:10, q:`Which line is <b>decreasing</b> (goes down as x increases)?`, choices:[`y = 2x + 5`,`y = −2x + 5`,`y = 5`,`y = x`], ans:1, hints:[`Negative slope.`], sol:`<b>y = −2x + 5.</b> (y = 5 is flat: slope 0.)` },
    ],
    apply:{ title:'Sliders', intro:`<p>Desmos makes m and b into physical objects you can push around. Do that until it's boring.</p>`,
      steps:[`Desmos: type <code>y = mx + b</code>. Click "add all sliders."`,`Drag b. The line moves up and down without tilting. That's the start.`,`Drag m. The line tilts around the intercept. That's the rate. Make m negative. Make it 0.`,`Now type your three real-life lines from the notebook. Do they look right? Does the intercept make sense?`,`Sheets: a "Line builder" tab. B1 = m, B2 = b. Column A: x from 0 to 10. Column C: <code>=$B$1*A2+$B$2</code> (the $ signs lock the cell; you'll learn why by dragging without them). Chart it. Change B1 and watch the chart tilt.`],
      checklist:[`Played with both sliders in Desmos`,`Three real-life lines graphed`,`Sheets line builder with locked cells ($B$1) and a chart`],
      dad:`The $B$1 trick (absolute references) is the most useful Sheets skill after fill-down. If he asks why, have him try the formula without the $ and drag it: it'll grab the wrong cells and the error explains itself.`
    },
  },
  // ---------------------------------------------------------------- S6
  {
    id:'u1s6', week:2, day:2, title:'Solving for x', subtitle:'An equation is a balance. Undo what was done. And the trick, explained twice.', tags:['magic','greek'],
    warmup:{ q:`3x = 21. What is x?`, type:'num', ans:7, tol:0, reveal:`<b>7.</b> Undo the "times 3" by dividing both sides by 3. That's the whole method, just with more steps.` },
    story:[
      {t:'h', html:'The balance'},
      {t:'p', html:`<p>An equation says two things weigh the same. 3x + 2 = 17 says "three x's and a 2 balance a 17." To find x, you're allowed to do <i>anything</i> to the scale, as long as you do it to both sides. Take 2 off both sides: 3x = 15. Split both sides into thirds: x = 5. The scale never tipped, so the answer is honest.</p>`},
      {t:'decoder', term:'Solve', def:`Find the value of the variable that makes the equation true. Every legal move keeps both sides equal; the goal is to get the variable alone on one side.`, ex:`3x + 2 = 17 → 3x = 15 → x = 5. Check: 3(5) + 2 = 17. ✓ Always check. It takes five seconds and catches everything.`},
      {t:'decoder', term:'Inverse operation', def:`The move that undoes another move. Subtracting undoes adding. Dividing undoes multiplying. Solving is running the machine backwards: undo the last thing first.`, ex:`The machine did ×3 then +2. To undo: −2 first, then ÷3. Last in, first out, like unpacking a bag.`},
      {t:'thread', kind:'example', title:'Two-step, then variables on both sides', html:`<div class="formula">5x + 4 = 2x + 19</div><p>Get the x's together: subtract 2x from both sides → 3x + 4 = 19. Subtract 4 → 3x = 15. Divide by 3 → <b>x = 5</b>. Check: 5(5) + 4 = 29 and 2(5) + 19 = 29. ✓</p><p>Real version: Yamal's distance = Ronaldo's distance. That's Session 9, and it's the Labor.</p>`},
      {t:'thread', kind:'example', title:'When does the storm kill you?', html:`<p>Phase 3: H = 100 − 5t. "When is health zero?" is the equation 100 − 5t = 0. Add 5t to both sides: 100 = 5t. Divide: <b>t = 20 seconds</b>. Every "how long until" question is an equation waiting to be solved.</p>`},
      {t:'thread', kind:'magic', title:'Why the trick works, and how to build your own', html:`<p>"Double, add 10, halve, subtract original" ends at 5 because (2n + 10) ÷ 2 − n = n + 5 − n = 5. The n cancels. Now you can design tricks:</p><div class="formula">n → ×a → +b → ÷a → −n &nbsp;=&nbsp; b ÷ a</div><p>Pick any a and b. Make b a multiple of a so the answer is a whole number. "Multiply by 4, add 12, divide by 4, subtract your number" → 3. "Multiply by 5, add 35, divide by 5, subtract your number" → 7. Add theater: "concentrate on your number... I'm sensing a 7."</p><p>Fancier: have them add their <i>age</i> somewhere and you can extract it, because you know everything except one thing. Willman badge for a trick you designed yourself, performed, and explained.</p>`},
      {t:'thread', kind:'greek', title:'Diophantus, and the word "algebra"', html:`<p>Diophantus of Alexandria (around 250 AD) wrote the first book that solved equations with symbols instead of words. The word <i>algebra</i> came later, from the Arabic <i>al-jabr</i> ("restoring"), the title of a book by al-Khwarizmi in Baghdad around 820 AD. Al-jabr meant moving a term to the other side of the balance. You'll do it twenty times today.</p><p>Diophantus's tombstone was reportedly a puzzle about his own life. It's Problem 8. Solve it and you know how old he was when he died.</p>`},
      {t:'thread', kind:'paper', html:`Codex: <i>solve</i>, <i>inverse operation</i>. Design your own number trick using the formula, write the n-table proof, and perform it tonight.`},
    ],
    practice:[
      { id:'u1s6p1', type:'num', xp:10, q:`4x − 6 = 18`, ans:6, tol:0, paper:true, hints:[`Undo the −6 first: add 6 to both sides.`,`4x = 24.`], sol:`4x = 24 → <b>x = 6</b>. Check: 24 − 6 = 18. ✓` },
      { id:'u1s6p2', type:'num', xp:10, q:`<span class="frac"><span>x</span><span>5</span></span> + 3 = 10`, ans:35, tol:0, paper:true, hints:[`Subtract 3 first.`,`x/5 = 7. Undo the ÷5.`], sol:`x/5 = 7 → <b>x = 35</b>.` },
      { id:'u1s6p3', type:'num', xp:10, q:`2x + 7 = 4x − 5`, ans:6, tol:0, paper:true, hints:[`Get x's on one side: subtract 2x from both sides.`,`7 = 2x − 5. Now add 5.`], sol:`12 = 2x → <b>x = 6</b>. Check: 19 = 19. ✓` },
      { id:'u1s6p4', type:'num', xp:10, q:`Storm phase 4 (7 HP/s): H = 100 − 7t. Solve for the time when H = 30. One decimal.`, ans:10, tol:0.05, unit:'s', hints:[`100 − 7t = 30.`,`70 = 7t.`], sol:`7t = 70 → <b>t = 10 s</b>.` },
      { id:'u1s6p5', type:'num', xp:10, q:`Server: P = 0.18s + 99. How much in sales to take home <b>$200</b>? Nearest dollar.`, ans:561, tol:1, unit:'dollars in sales', hints:[`0.18s + 99 = 200.`,`0.18s = 101. Divide.`], sol:`s = 101 ÷ 0.18 ≈ <b>$561</b> in sales. A busy night at a mid-priced place.` },
      { id:'u1s6p6', type:'num', xp:10, q:`Rubik's: T = 60 − 2w. When does the average hit <b>30 s</b>?`, ans:15, tol:0, unit:'weeks', hints:[`60 − 2w = 30.`], sol:`2w = 30 → <b>w = 15 weeks</b>.` },
      { id:'u1s6p7', type:'num', xp:10, tags:['magic'], q:`Design check: "Multiply your number by 4, add 12, divide by 4, subtract your number." Everyone gets:`, ans:3, tol:0, hints:[`b ÷ a.`], sol:`12 ÷ 4 = <b>3</b>. (4n + 12) ÷ 4 − n = n + 3 − n = 3.` },
      { id:'u1s6p8', type:'num', xp:15, tags:['greek'], paper:true, q:`<b>Diophantus's tombstone</b> (paraphrased): "He was a boy for one-sixth of his life. After one-twelfth more, he grew a beard. After one-seventh more, he married. Five years later a son was born. The son lived half as long as his father. Four years after the son died, Diophantus died." How old was Diophantus?`, ans:84, tol:0, hints:[`Call his age x. Write every piece: x/6 + x/12 + x/7 + 5 + x/2 + 4 = x.`,`Fractions are annoying. Multiply <i>every</i> term by 84 (the smallest number 6, 12, 7, and 2 all divide into).`,`14x + 7x + 12x + 420 + 42x + 336 = 84x. Collect.`], sol:`75x + 756 = 84x → 756 = 9x → <b>x = 84</b>. Boy until 14, beard at 21, married at 33, son at 38, son died at 80, Diophantus at 84. Slightly grim for a tombstone, but he'd have liked that you solved it.` },
    ],
    apply:{ title:'Perform and prove', intro:`<p>Your own trick, tonight. The math first, the theater second.</p>`,
      steps:[`Pick a and b (make b a multiple of a). Write the full n-table proof in the notebook.`,`Rehearse the patter. Pauses. Eye contact. "Are you sure you're concentrating?"`,`Perform for Dad. Then hand him the n-table and make him explain it back to you. (Yes, reversed. Teaching is how you find out whether you know it.)`,`Claude: paste your trick's steps and ask "Check my algebra. Don't tell me if it works; tell me if my proof has a gap." See what it says. If it makes a mistake, you know what to do.`],
      checklist:[`Trick designed with a written proof`,`Performed for at least one person`,`Claude reviewed the proof (and you reviewed Claude)`],
      dad:`Willman badge criteria: a trick he designed (not the one from Unit 0), performed with some showmanship, and explained clearly enough that you could repeat it. Award from the Badges page. If he wants a harder version: have the spectator add their shoe size or age at some step, and have him work out how to extract it.`
    },
  },
  ]
});
